### ISSUE TITLE
Error: specified PCM format is not supported by "win32" backend

### ISSUE THREAD

**Issue by kythre** [TooTallNate/node-speaker#125]
> [23:17:17] Unhandled Exception Error  
log.js:17
Error: specified PCM format is not supported by "win32" backend
    at Speaker._open (d:\Development\discord-kylesbot\node_modules\speaker\index.js:157:11)
    at Speaker._write (d:\Development\discord-kylesbot\node_modules\speaker\index.js:242:21)
    at doWrite (d:\Development\discord-kylesbot\node_modules\readable-stream\lib\_stream_writable.js:428:64)
    at writeOrBuffer (d:\Development\discord-kylesbot\node_modules\readable-stream\lib\_stream_writable.js:417:5)
    at Speaker.Writable.write (d:\Development\discord-kylesbot\node_modules\readable-stream\lib\_stream_writable.js:334:11)
    at AudioSpeaker.ondata (_stream_readable.js:666:20)
    at AudioSpeaker.emit (events.js:182:13)
    at AudioSpeaker.Readable.read (_stream_readable.js:486:10)
    at flow (_stream_readable.js:922:34)
    at resume_ (_stream_readable.js:904:3)

**Comment by richiedevs** [comment]
I'm also getting this issue recently

**Comment by PolPtoAmo** [comment]
Getting this issue too. Looks like it occurs when trying to play more than 16 bits. Updating windows advanced sound thing to play 48000Hz doesn't work
