### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by LinusU** [TooTallNate/node-speaker#21]
Something is leaking when piping to the speaker module. This first example will run on forever without problems (well, til your out of free space). The second example will output an warning after ~22 seconds.

``` text
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at RandStream.EventEmitter.addListener (events.js:160:15)
    at RandStream.Readable.on (/tmp/node_modules/randstream/node_modules/readable-stream/lib/_stream_readable.js:589:33)
    at RandStream.EventEmitter.once (events.js:179:8)
    at Speaker._pipe (/tmp/node_modules/speaker/index.js:228:10)
    at Speaker.EventEmitter.emit (events.js:95:17)
    at RandStream.Readable.pipe (/tmp/node_modules/randstream/node_modules/readable-stream/lib/_stream_readable.js:446:8)
    at null._onTimeout (/tmp/test.js:17:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
```

**test-1.js**

``` javascript
var fs = require('fs');
var RandStream = require('randstream');

var s = null;
var firehose = new RandStream();

var repipe = function () {
  if(s) {
    console.log('unpipe');
    firehose.unpipe(s);
    s.end();
  }
  setTimeout(function () {
    s = fs.createWriteStream('/tmp/' + +(new Date));
    console.log('pipe');
    firehose.pipe(s);
  }, 1000);
};

setInterval(repipe, 2000);
```

**test-2.js**

``` javascript
var Speaker = require('speaker');
var RandStream = require('randstream');

var s = null;
var firehose = new RandStream();

var repipe = function () {
  if(s) {
    console.log('unpipe');
    firehose.unpipe(s);
    s.end();
  }
  setTimeout(function () {
    s = new Speaker();
    console.log('pipe');
    firehose.pipe(s);
  }, 1000);
};

setInterval(repipe, 2000);
```

**Comment by boedy** [comment]
@LinusU In your tests I notice you are waiting one second between ending the the speaker instance and reinitialising it. Have you pinpointed the reason why this is needed?

I'm currently experiencing issues when a new Speaker instance is reconstructed too fast after ending.
