### ISSUE TITLE
failed to install v0.2.5 on OS X 10.10.3 with io.js v2.0.1

### ISSUE THREAD

**Issue by leungwensen** [TooTallNate/node-speaker#53]
logs:

```shell
    909 verbose rebuildBundles [ 'bindings', 'debug', 'nan', 'readable-stream' ]
    910 info install speaker@0.2.5
    911 verbose unsafe-perm in lifecycle true
    912 info speaker@0.2.5 Failed to exec install script
    913 verbose unlock done using /Users/liangwensen/.npm/_locks/speaker-426051877ea3cabd.lock for /Users/liangwensen/.nvm/versions/io.js/v2.0.1/lib/node_modules/speaker
    914 verbose stack Error: speaker@0.2.5 install: `node-gyp rebuild`
    914 verbose stack Exit status 1
    914 verbose stack     at EventEmitter.<anonymous> (/Users/liangwensen/.nvm/versions/io.js/v2.0.1/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
    914 verbose stack     at emitTwo (events.js:87:13)
    914 verbose stack     at EventEmitter.emit (events.js:169:7)
    914 verbose stack     at ChildProcess.<anonymous> (/Users/liangwensen/.nvm/versions/io.js/v2.0.1/lib/node_modules/npm/lib/utils/spawn.js:24:14)
    914 verbose stack     at emitTwo (events.js:87:13)
    914 verbose stack     at ChildProcess.emit (events.js:169:7)
    914 verbose stack     at maybeClose (child_process.js:953:16)
    914 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1020:5)
    915 verbose pkgid speaker@0.2.5
    916 verbose cwd /Users/liangwensen
    917 error Darwin 14.3.0
    918 error argv "/Users/liangwensen/.nvm/versions/io.js/v2.0.1/bin/iojs" "/Users/liangwensen/.nvm/versions/io.js/v2.0.1/bin/npm" "install" "speaker" "-g"
    919 error node v2.0.1
    920 error npm  v2.9.0
    921 error code ELIFECYCLE
    922 error speaker@0.2.5 install: `node-gyp rebuild`
    922 error Exit status 1
    923 error Failed at the speaker@0.2.5 install script 'node-gyp rebuild'.
    923 error This is most likely a problem with the speaker package,
    923 error not with npm itself.
    923 error Tell the author that this fails on your system:
    923 error     node-gyp rebuild
    923 error You can get their info via:
    923 error     npm owner ls speaker
    923 error There is likely additional logging output above.
```

environment:

* mac osx 10.10.3
* nvm - using io.js v2.0.1

need your help here, thanks!

**Comment by seppevs** [comment]
I have the same issue on Linux:

```bash
5876 verbose unlock done using /home/pi/.npm/_locks/lame-d990ccdfffb79554.lock for /home/pi/speech/node_modules/say-something/node_modules/lame
5877 verbose about to build /home/pi/speech/node_modules/say-something
5878 verbose unlock done using /home/pi/.npm/_locks/say-something-b3e8101fb89068cf.lock for /home/pi/speech/node_modules/say-something
5879 verbose stack Error: speaker@0.2.5 install: `node-gyp rebuild`
5879 verbose stack Exit status 1
5879 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
5879 verbose stack     at EventEmitter.emit (events.js:110:17)
5879 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
5879 verbose stack     at ChildProcess.emit (events.js:110:17)
5879 verbose stack     at maybeClose (child_process.js:1008:16)
5879 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
5880 verbose pkgid speaker@0.2.5
5881 verbose cwd /home/pi/speech
5882 error Linux 3.18.11+
5883 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "say-something" "--save"
5884 error node v0.12.0
5885 error npm  v2.5.1
5886 error code ELIFECYCLE
5887 error speaker@0.2.5 install: `node-gyp rebuild`
5887 error Exit status 1
5888 error Failed at the speaker@0.2.5 install script 'node-gyp rebuild'.
5888 error This is most likely a problem with the speaker package,
5888 error not with npm itself.
5888 error Tell the author that this fails on your system:
5888 error     node-gyp rebuild
5888 error You can get their info via:
5888 error     npm owner ls speaker
5888 error There is likely additional logging output above.
5889 verbose exit [ 1, true ]
5890 verbose unbuild node_modules/say-something/node_modules/speaker
```

**Comment by bjackson** [comment]
I'm getting the same thing. I'm on Yosemite.

**Comment by gordomium** [comment]
+1

**Comment by justinmchase** [comment]
I believe the nan module needs to be udpated to 1.8.4, then this should be fixed.
