### ISSUE TITLE
Install fails on 5.9.0

### ISSUE THREAD

**Issue by IonicaBizau** [TooTallNate/node-speaker#75]
```sh
$ node --version
v5.9.0
```

The installation fails. Here are some relevant logs:

```sh
0 info it worked if it ends with ok
1 verbose cli [ '/home/ionicabizau/.nvm/versions/node/v5.9.0/bin/node',
1 verbose cli   '/home/ionicabizau/.nvm/versions/node/v5.9.0/bin/npm',
1 verbose cli   'i' ]
2 info using npm@3.7.3
3 info using node@v5.9.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly install loadAllDepsIntoIdealTree
19 silly loadAllDepsIntoIdealTree Finishing
20 silly idealTree:prePrune speaker@0.2.6
20 silly idealTree:prePrune ├── bindings@1.2.1
20 silly idealTree:prePrune ├── commander@2.3.0
20 silly idealTree:prePrune ├── core-util-is@1.0.2
20 silly idealTree:prePrune ├── debug@2.2.0
20 silly idealTree:prePrune ├── diff@1.0.8
20 silly idealTree:prePrune ├── escape-string-regexp@1.0.2
20 silly idealTree:prePrune ├── glob@3.2.3
20 silly idealTree:prePrune ├── graceful-fs@2.0.3
20 silly idealTree:prePrune ├── growl@1.8.1
20 silly idealTree:prePrune ├── inherits@2.0.1
20 silly idealTree:prePrune ├── isarray@0.0.1
20 silly idealTree:prePrune ├─┬ jade@0.26.3
20 silly idealTree:prePrune │ ├── commander@0.6.1
20 silly idealTree:prePrune │ └── mkdirp@0.3.0
20 silly idealTree:prePrune ├── lru-cache@2.7.3
20 silly idealTree:prePrune ├── minimatch@0.2.14
20 silly idealTree:prePrune ├── minimist@0.0.8
20 silly idealTree:prePrune ├── mkdirp@0.5.0
20 silly idealTree:prePrune ├─┬ mocha@2.1.0
20 silly idealTree:prePrune │ ├── debug@2.0.0
20 silly idealTree:prePrune │ └── ms@0.6.2
20 silly idealTree:prePrune ├── ms@0.7.1
20 silly idealTree:prePrune ├── nan@2.2.0
20 silly idealTree:prePrune ├── readable-stream@1.0.33
20 silly idealTree:prePrune ├── sigmund@1.0.1
20 silly idealTree:prePrune └── string_decoder@0.10.31
21 silly loadIdealTree Finishing
22 silly currentTree speaker@0.2.6
22 silly currentTree ├── bindings@1.2.1
22 silly currentTree ├── commander@2.3.0
22 silly currentTree ├── core-util-is@1.0.2
22 silly currentTree ├── debug@2.2.0
22 silly currentTree ├── diff@1.0.8
22 silly currentTree ├── escape-string-regexp@1.0.2
22 silly currentTree ├── glob@3.2.3
22 silly currentTree ├── graceful-fs@2.0.3
22 silly currentTree ├── growl@1.8.1
22 silly currentTree ├── inherits@2.0.1
22 silly currentTree ├── isarray@0.0.1
22 silly currentTree ├─┬ jade@0.26.3
22 silly currentTree │ ├── commander@0.6.1
22 silly currentTree │ └── mkdirp@0.3.0
22 silly currentTree ├── lru-cache@2.7.3
22 silly currentTree ├── minimatch@0.2.14
22 silly currentTree ├── minimist@0.0.8
22 silly currentTree ├── mkdirp@0.5.0
22 silly currentTree ├─┬ mocha@2.1.0
22 silly currentTree │ ├── debug@2.0.0
22 silly currentTree │ └── ms@0.6.2
22 silly currentTree ├── ms@0.7.1
22 silly currentTree ├── nan@2.2.0
22 silly currentTree ├── readable-stream@1.0.33
22 silly currentTree ├── sigmund@1.0.1
22 silly currentTree └── string_decoder@0.10.31
23 silly idealTree speaker@0.2.6
23 silly idealTree ├── bindings@1.2.1
23 silly idealTree ├── commander@2.3.0
23 silly idealTree ├── core-util-is@1.0.2
23 silly idealTree ├── debug@2.2.0
23 silly idealTree ├── diff@1.0.8
23 silly idealTree ├── escape-string-regexp@1.0.2
23 silly idealTree ├── glob@3.2.3
23 silly idealTree ├── graceful-fs@2.0.3
23 silly idealTree ├── growl@1.8.1
23 silly idealTree ├── inherits@2.0.1
23 silly idealTree ├── isarray@0.0.1
23 silly idealTree ├─┬ jade@0.26.3
23 silly idealTree │ ├── commander@0.6.1
23 silly idealTree │ └── mkdirp@0.3.0
23 silly idealTree ├── lru-cache@2.7.3
23 silly idealTree ├── minimatch@0.2.14
23 silly idealTree ├── minimist@0.0.8
23 silly idealTree ├── mkdirp@0.5.0
23 silly idealTree ├─┬ mocha@2.1.0
23 silly idealTree │ ├── debug@2.0.0
23 silly idealTree │ └── ms@0.6.2
23 silly idealTree ├── ms@0.7.1
23 silly idealTree ├── nan@2.2.0
23 silly idealTree ├── readable-stream@1.0.33
23 silly idealTree ├── sigmund@1.0.1
23 silly idealTree └── string_decoder@0.10.31
24 silly generateActionsToTake Starting
25 silly install generateActionsToTake
26 silly generateActionsToTake Finishing
27 silly diffTrees action count 0
28 silly decomposeActions action count 0
29 silly executeActions Starting
30 silly install executeActions
31 silly doSerial global-install 0
32 silly doParallel fetch 0
33 verbose correctMkdir /home/ionicabizau/.npm/_locks correctMkdir not in flight; initializing
34 verbose lock using /home/ionicabizau/.npm/_locks/staging-27811545794f7f00.lock for /home/ionicabizau/.../speaker/node_modules/.staging
35 silly doParallel extract 0
36 silly doParallel preinstall 0
37 silly doReverseSerial remove 0
38 silly doSerial move 0
39 silly doSerial finalize 0
40 silly doSerial build 0
41 silly doSerial global-link 0
42 silly doParallel update-linked 0
43 silly doSerial install 0
44 silly doSerial postinstall 0
45 verbose unlock done using /home/ionicabizau/.npm/_locks/staging-27811545794f7f00.lock for /home/ionicabizau/.../speaker/node_modules/.staging
46 silly executeActions Finishing
47 silly rollbackFailedOptional Starting
48 silly rollbackFailedOptional Finishing
49 silly runTopLevelLifecycles Starting
50 silly install runTopLevelLifecycles
51 silly preinstall speaker@0.2.6 /home/ionicabizau/.../speaker/speaker-69c73cab
52 info lifecycle speaker@0.2.6~preinstall: speaker@0.2.6
53 silly lifecycle speaker@0.2.6~preinstall: no script for preinstall, continuing
54 silly build speaker@0.2.6
55 info linkStuff speaker@0.2.6
56 silly linkStuff speaker@0.2.6 has /home/ionicabizau/... as its parent node_modules
57 verbose linkBins speaker@0.2.6
58 verbose linkMans speaker@0.2.6
59 silly install speaker@0.2.6 /home/ionicabizau/.../speaker/speaker-69c73cab
60 info lifecycle speaker@0.2.6~install: speaker@0.2.6
61 verbose lifecycle speaker@0.2.6~install: unsafe-perm in lifecycle true
62 verbose lifecycle speaker@0.2.6~install: PATH: /home/ionicabizau/.nvm/versions/node/v5.9.0/lib/node_modules/npm/bin/node-gyp-bin:/home/ionicabizau/.../speaker/node_modules/.bin:/home/ionicabizau/.../.bin:/home/ionicabizau/Documents/audiify/node_modules/.bin:/home/ionicabizau/.nvm/versions/node/v5.9.0/bin:/home/ionicabizau/.nvm/versions/node/v5.9.0/bin:/home/ionicabizau/.node/bin:/home/ionicabizau/.node/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/ionicabizau/.rvm/bin:/home/ionicabizau/.rvm/bin
63 verbose lifecycle speaker@0.2.6~install: CWD: /home/ionicabizau/.../speaker
64 silly lifecycle speaker@0.2.6~install: Args: [ '-c', 'node-gyp rebuild' ]
65 silly lifecycle speaker@0.2.6~install: Returned: code: 1  signal: null
66 info lifecycle speaker@0.2.6~install: Failed to exec install script
67 warn speaker@0.2.6 No license field.
68 verbose stack Error: speaker@0.2.6 install: `node-gyp rebuild`
68 verbose stack Exit status 1
68 verbose stack     at EventEmitter.<anonymous> (/home/ionicabizau/.nvm/versions/node/v5.9.0/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
68 verbose stack     at emitTwo (events.js:100:13)
68 verbose stack     at EventEmitter.emit (events.js:185:7)
68 verbose stack     at ChildProcess.<anonymous> (/home/ionicabizau/.nvm/versions/node/v5.9.0/lib/node_modules/npm/lib/utils/spawn.js:24:14)
68 verbose stack     at emitTwo (events.js:100:13)
68 verbose stack     at ChildProcess.emit (events.js:185:7)
68 verbose stack     at maybeClose (internal/child_process.js:850:16)
68 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
69 verbose pkgid speaker@0.2.6
70 verbose cwd /home/ionicabizau/.../speaker
71 error Linux 4.4.0-15-generic
72 error argv "/home/ionicabizau/.nvm/versions/node/v5.9.0/bin/node" "/home/ionicabizau/.nvm/versions/node/v5.9.0/bin/npm" "i"
73 error node v5.9.0
74 error npm  v3.7.3
75 error code ELIFECYCLE
76 error speaker@0.2.6 install: `node-gyp rebuild`
76 error Exit status 1
77 error Failed at the speaker@0.2.6 install script 'node-gyp rebuild'.
77 error Make sure you have the latest version of node.js and npm installed.
77 error If you do, this is most likely a problem with the speaker package,
77 error not with npm itself.
77 error Tell the author that this fails on your system:
77 error     node-gyp rebuild
77 error You can get information on how to open an issue for this project with:
77 error     npm bugs speaker
77 error Or if that isn't available, you can get their info via:
77 error     npm owner ls speaker
77 error There is likely additional logging output above.
78 verbose exit [ 1, true ]
```

**Comment by IonicaBizau** [comment]
Fixed by `sudo apt-get install libasound2-dev`. I guess it would be nice to have a friendlier error if this is not installed.
