### ISSUE TITLE
Raspbian installation node-gyp error

### ISSUE THREAD

**Issue by a-x-** [TooTallNate/node-speaker#88]
moved from https://github.com/fraserxu/music163-cli/issues/9

sudo npm install -g n
curl -0 -L http://npmjs.org/install.sh | sudo sh
sudo n latest

sudo apt-get install libasound2-dev
sudo npm i -g music163-cli:
```
...
... successful compiling some things with a lot of warnings, then error:
...
../node_modules/nan/nan.h:578:36: note:   candidate expects 1 argument, 4 provided
binding.target.mk:97: ошибка выполнения рецепта для цели «Release/obj.target/binding/src/binding.o»
make: *** [Release/obj.target/binding/src/binding.o] Ошибка 1
make: выход из каталога «/usr/lib/node_modules/music163-cli/node_modules/speaker/build»
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.13+
gyp ERR! command "/usr/bin/nodejs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/music163-cli/node_modules/speaker
gyp ERR! node -v v6.6.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
[               ...] \ install: info lifecycle speaker@0.2.5~install: Failed to exec install script
/usr/lib
└── (empty)

npm ERR! Linux 4.4.13+
npm ERR! argv "/usr/bin/nodejs" "/usr/local/bin/npm" "i" "-g" "music163-cli"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! speaker@0.2.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the speaker@0.2.5 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the speaker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs speaker
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls speaker
npm ERR! There is likely additional logging output above.
```

node v6.6.0
npm v3.10.3
gcc --version
gcc (Raspbian 4.9.2-10) 4.9.2

**Comment by LinusU** [comment]
Could you please translate these strings for me :)

> ошибка выполнения рецепта для цели

> выход из каталога

**Comment by a-x-** [comment]
execution target error
exit directory

**Comment by a-x-** [comment]
ping
